image: docker/compose:latest
services:
  - docker:dind
stages:
  # - build
  # - test
  - deploy
default:
  before_script:
    - ./deploy/env.sh
    - cp ./deploy/docker-compose.yml.example ./deploy/docker-compose.yml
    - docker info
    - docker-compose --version

# test:
#   stage: test
#   only:
#     - dev
#   script:
#     - echo running tests in test

deploy-dev:
  stage: deploy
  only:
    - dev
  script:
    - cd ./deploy;
    - docker-compose up --build -d

deploy-dev:
  stage: deploy
  only:
    - trial
  script:
    - docker build -t lucis_launchpad_trial:$CI_COMMIT_SHORT_SHA -f deploy/Dockerfile .
    - docker run -p 3001:3000 --restart always --network lucis_network --name lucis_launchpad_trial lucis_launchpad_trial:$CI_COMMIT_SHORT_SHA

deploy-prod:
  stage: deploy
  only:
    - main
  script:
    - ./deploy/deploy.sh
  when: manual
